version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootroot
      POSTGRES_DB: redorange
    ports:
      - "5432:5432"
    restart:
      always
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart:
      always
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: rootroot
    ports:
      - "27017:27017"
    restart:
      always
    