# Generated by Django 3.0.5 on 2020-05-04 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partya',
            name='boss',
            field=models.ForeignKey(help_text='老板', on_delete=django.db.models.deletion.PROTECT, related_name='boss_partya', to=settings.AUTH_USER_MODEL, verbose_name='老板'),
        ),
        migrations.AddField(
            model_name='partya',
            name='workers',
            field=models.ManyToManyField(help_text='员工', related_name='workers_partya', to=settings.AUTH_USER_MODEL, verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='party_a',
            field=models.ForeignKey(help_text='甲方', on_delete=django.db.models.deletion.CASCADE, to='ads.PartyA', verbose_name='甲方'),
        ),
    ]
