# Generated by Django 3.0.5 on 2020-05-02 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('code', models.IntegerField(help_text='编码', primary_key=True, serialize=False, verbose_name='编码')),
                ('name', models.CharField(help_text='名称', max_length=15, verbose_name='名称')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('code', models.IntegerField(help_text='编码', primary_key=True, serialize=False, verbose_name='编码')),
                ('name', models.CharField(help_text='名称', max_length=15, verbose_name='名称')),
                ('province', models.ForeignKey(help_text='省份', on_delete=django.db.models.deletion.CASCADE, to='others.Province', verbose_name='省份')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('code', models.IntegerField(help_text='编码', primary_key=True, serialize=False, verbose_name='编码')),
                ('name', models.CharField(help_text='名称', max_length=15, verbose_name='名称')),
                ('city', models.ForeignKey(help_text='城市', on_delete=django.db.models.deletion.CASCADE, to='others.City', verbose_name='城市')),
            ],
            options={
                'verbose_name': '区县',
                'verbose_name_plural': '区县',
            },
        ),
    ]
