# Generated by Django 3.0.6 on 2020-05-11 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('code', models.IntegerField(help_text='编码', primary_key=True, serialize=False, verbose_name='编码')),
                ('name', models.CharField(help_text='名称', max_length=25, verbose_name='名称')),
            ],
            options={
                'verbose_name': '岗位一级分类',
                'verbose_name_plural': '岗位一级分类',
            },
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(help_text='名称', max_length=25, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(help_text='名称', max_length=25, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(help_text='名称', max_length=25, verbose_name='名称'),
        ),
        migrations.CreateModel(
            name='JobSubCategory',
            fields=[
                ('code', models.IntegerField(help_text='编码', primary_key=True, serialize=False, verbose_name='编码')),
                ('name', models.CharField(help_text='名称', max_length=25, verbose_name='名称')),
                ('category', models.ForeignKey(help_text='岗位一级分类', on_delete=django.db.models.deletion.CASCADE, to='others.JobCategory', verbose_name='岗位一级分类')),
            ],
            options={
                'verbose_name': '岗位二级分类',
                'verbose_name_plural': '岗位二级分类',
            },
        ),
    ]
