# Generated by Django 3.0.6 on 2020-05-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brithday',
            field=models.DateField(help_text='出生日期', null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='checked_in',
            field=models.BooleanField(blank=True, default=False, help_text='是否打卡', verbose_name='是否打卡'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(1, '男'), (0, '女'), (2, '未知')], default=2, help_text='标识符申请状态', verbose_name='标识符申请状态'),
        ),
    ]
