# Generated by Django 3.0.6 on 2020-05-11 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('others', '0002_auto_20200511_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='岗位', max_length=10, verbose_name='岗位')),
                ('pay', models.CharField(help_text='薪资待遇', max_length=20, verbose_name='薪资待遇')),
                ('descriptions', models.CharField(help_text='工作描述', max_length=200, verbose_name='工作描述')),
                ('requirements', models.CharField(help_text='岗位要求', max_length=200, verbose_name='岗位要求')),
                ('benefits', models.CharField(blank=True, default='', help_text='福利', max_length=100, verbose_name='福利')),
                ('category', models.ForeignKey(blank=True, help_text='岗位一级分类', null=True, on_delete=django.db.models.deletion.SET_NULL, to='others.JobCategory', verbose_name='岗位一级分类')),
                ('sub_category', models.ForeignKey(blank=True, help_text='岗位二级分类', null=True, on_delete=django.db.models.deletion.SET_NULL, to='others.JobSubCategory', verbose_name='岗位二级分类')),
                ('user', models.ForeignKey(help_text='用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '个人工作',
                'verbose_name_plural': '个人工作',
            },
        ),
        migrations.CreateModel(
            name='PartTimeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='岗位', max_length=10, verbose_name='岗位')),
                ('pay', models.CharField(help_text='薪资待遇', max_length=20, verbose_name='薪资待遇')),
                ('descriptions', models.CharField(help_text='工作描述', max_length=200, verbose_name='工作描述')),
                ('requirements', models.CharField(help_text='岗位要求', max_length=200, verbose_name='岗位要求')),
                ('benefits', models.CharField(blank=True, default='', help_text='福利', max_length=100, verbose_name='福利')),
                ('category', models.ForeignKey(blank=True, help_text='岗位一级分类', null=True, on_delete=django.db.models.deletion.SET_NULL, to='others.JobCategory', verbose_name='岗位一级分类')),
                ('party_a', models.ForeignKey(help_text='甲方', on_delete=django.db.models.deletion.CASCADE, to='ads.PartyA', verbose_name='甲方')),
                ('sub_category', models.ForeignKey(blank=True, help_text='岗位二级分类', null=True, on_delete=django.db.models.deletion.SET_NULL, to='others.JobSubCategory', verbose_name='岗位二级分类')),
            ],
            options={
                'verbose_name': '企业兼职工作',
                'verbose_name_plural': '企业兼职工作',
            },
        ),
        migrations.CreateModel(
            name='FullTimeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(help_text='岗位', max_length=10, verbose_name='岗位')),
                ('pay', models.CharField(help_text='薪资待遇', max_length=20, verbose_name='薪资待遇')),
                ('descriptions', models.CharField(help_text='工作描述', max_length=200, verbose_name='工作描述')),
                ('requirements', models.CharField(help_text='岗位要求', max_length=200, verbose_name='岗位要求')),
                ('benefits', models.CharField(blank=True, default='', help_text='福利', max_length=100, verbose_name='福利')),
                ('category', models.ForeignKey(blank=True, help_text='岗位一级分类', null=True, on_delete=django.db.models.deletion.SET_NULL, to='others.JobCategory', verbose_name='岗位一级分类')),
                ('party_a', models.ForeignKey(help_text='甲方', on_delete=django.db.models.deletion.CASCADE, to='ads.PartyA', verbose_name='甲方')),
                ('sub_category', models.ForeignKey(blank=True, help_text='岗位二级分类', null=True, on_delete=django.db.models.deletion.SET_NULL, to='others.JobSubCategory', verbose_name='岗位二级分类')),
            ],
            options={
                'verbose_name': '企业全职工作',
                'verbose_name_plural': '企业全职工作',
            },
        ),
    ]
